# Generated by Django 4.1.4 on 2023-04-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='company_type',
            field=models.CharField(default='it', max_length=200),
            preserve_default=False,
        ),
    ]
