# Generated by Django 4.1.4 on 2023-04-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_companyprofile_company_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='company_type',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='about',
            field=models.CharField(default='dcfvg', max_length=500),
            preserve_default=False,
        ),
    ]
