# Generated by Django 4.1.4 on 2023-04-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_companyprofile_company_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='ready_to_relocate',
            field=models.BooleanField(default=False),
        ),
    ]
