# Generated by Django 4.1.4 on 2023-04-28 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_candidateprofile_ready_to_relocate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='about',
        ),
    ]
