# Generated by Django 4.1.4 on 2023-04-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_companyprofile_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='description',
            field=models.CharField(default='drcftvgbhndcfvgbhnjdrcftvgybhn', max_length=500),
            preserve_default=False,
        ),
    ]
