# Generated by Django 4.1.4 on 2023-04-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='gender',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male'), ('others', 'others')], max_length=10),
        ),
    ]
