# Generated by Django 4.1.4 on 2023-04-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_candidateprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
