# Generated by Django 4.1.4 on 2023-04-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_candidateprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accept', 'accept'), ('reject', 'reject'), ('cancelled', 'cancelled')], default='pending', max_length=200),
        ),
    ]
